/* eslint-disable */
/* Auto-generated by scripts/gen-db-types.mjs — do not edit by hand. Re-run: npm run gen:db-types */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  graphql_public: {
    Tables: {
      [_ in never]: never
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      graphql: {
        Args: {
          extensions?: Json
          operationName?: string
          query?: string
          variables?: Json
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
  public: {
    Tables: {
      admission_applications: {
        Row: {
          address: string
          admin_notes: string | null
          child_age: string | null
          child_name: string
          created_at: string | null
          date_of_birth: string | null
          email: string
          emergency_contact: string | null
          emergency_phone: string | null
          gender: string | null
          id: string
          medical_conditions: string | null
          message: string | null
          parent_name: string
          phone: string
          previous_school: string | null
          program: string
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
        }
        Insert: {
          address: string
          admin_notes?: string | null
          child_age?: string | null
          child_name: string
          created_at?: string | null
          date_of_birth?: string | null
          email: string
          emergency_contact?: string | null
          emergency_phone?: string | null
          gender?: string | null
          id?: string
          medical_conditions?: string | null
          message?: string | null
          parent_name: string
          phone: string
          previous_school?: string | null
          program: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Update: {
          address?: string
          admin_notes?: string | null
          child_age?: string | null
          child_name?: string
          created_at?: string | null
          date_of_birth?: string | null
          email?: string
          emergency_contact?: string | null
          emergency_phone?: string | null
          gender?: string | null
          id?: string
          medical_conditions?: string | null
          message?: string | null
          parent_name?: string
          phone?: string
          previous_school?: string | null
          program?: string
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "admission_applications_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      announcements: {
        Row: {
          content: string
          created_at: string | null
          expires_at: string | null
          id: string
          priority: string | null
          published: boolean | null
          published_by: string | null
          target_audience: string[] | null
          title: string
        }
        Insert: {
          content: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          priority?: string | null
          published?: boolean | null
          published_by?: string | null
          target_audience?: string[] | null
          title: string
        }
        Update: {
          content?: string
          created_at?: string | null
          expires_at?: string | null
          id?: string
          priority?: string | null
          published?: boolean | null
          published_by?: string | null
          target_audience?: string[] | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "announcements_published_by_fkey"
            columns: ["published_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      assignments: {
        Row: {
          course_id: string | null
          created_at: string | null
          created_by: string | null
          description: string | null
          due_date: string | null
          id: string
          max_score: number | null
          title: string
          type: string | null
        }
        Insert: {
          course_id?: string | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          max_score?: number | null
          title: string
          type?: string | null
        }
        Update: {
          course_id?: string | null
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          due_date?: string | null
          id?: string
          max_score?: number | null
          title?: string
          type?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "assignments_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assignments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      attendance: {
        Row: {
          created_at: string | null
          date: string
          id: string
          marked_by: string | null
          notes: string | null
          status: Database["public"]["Enums"]["attendance_status"]
          student_id: string | null
        }
        Insert: {
          created_at?: string | null
          date?: string
          id?: string
          marked_by?: string | null
          notes?: string | null
          status?: Database["public"]["Enums"]["attendance_status"]
          student_id?: string | null
        }
        Update: {
          created_at?: string | null
          date?: string
          id?: string
          marked_by?: string | null
          notes?: string | null
          status?: Database["public"]["Enums"]["attendance_status"]
          student_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "attendance_marked_by_fkey"
            columns: ["marked_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "attendance_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_events: {
        Row: {
          action: string
          actor_profile_id: string | null
          created_at: string
          details: Json | null
          entity_id: string | null
          entity_type: string
          id: string
        }
        Insert: {
          action: string
          actor_profile_id?: string | null
          created_at?: string
          details?: Json | null
          entity_id?: string | null
          entity_type: string
          id?: string
        }
        Update: {
          action?: string
          actor_profile_id?: string | null
          created_at?: string
          details?: Json | null
          entity_id?: string | null
          entity_type?: string
          id?: string
        }
        Relationships: [
          {
            foreignKeyName: "audit_events_actor_profile_id_fkey"
            columns: ["actor_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cbt_answers: {
        Row: {
          created_at: string | null
          id: string
          question_id: string
          selected_option: string | null
          session_id: string
          updated_at: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          question_id: string
          selected_option?: string | null
          session_id: string
          updated_at?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          question_id?: string
          selected_option?: string | null
          session_id?: string
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cbt_answers_question_id_fkey"
            columns: ["question_id"]
            isOneToOne: false
            referencedRelation: "cbt_questions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cbt_answers_session_id_fkey"
            columns: ["session_id"]
            isOneToOne: false
            referencedRelation: "cbt_sessions"
            referencedColumns: ["id"]
          },
        ]
      }
      cbt_exams: {
        Row: {
          academic_year: string
          class_id: string | null
          created_at: string | null
          created_by: string | null
          duration_minutes: number
          end_time: string | null
          id: string
          instructions: string
          is_published: boolean
          start_time: string | null
          subject: string
          term: string
          title: string
          total_marks: number
          updated_at: string | null
        }
        Insert: {
          academic_year?: string
          class_id?: string | null
          created_at?: string | null
          created_by?: string | null
          duration_minutes?: number
          end_time?: string | null
          id?: string
          instructions?: string
          is_published?: boolean
          start_time?: string | null
          subject: string
          term?: string
          title: string
          total_marks?: number
          updated_at?: string | null
        }
        Update: {
          academic_year?: string
          class_id?: string | null
          created_at?: string | null
          created_by?: string | null
          duration_minutes?: number
          end_time?: string | null
          id?: string
          instructions?: string
          is_published?: boolean
          start_time?: string | null
          subject?: string
          term?: string
          title?: string
          total_marks?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cbt_exams_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cbt_exams_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cbt_questions: {
        Row: {
          correct_option: string
          created_at: string | null
          exam_id: string
          id: string
          marks: number
          option_a: string
          option_b: string
          option_c: string
          option_d: string
          order_index: number
          question_text: string
        }
        Insert: {
          correct_option: string
          created_at?: string | null
          exam_id: string
          id?: string
          marks?: number
          option_a?: string
          option_b?: string
          option_c?: string
          option_d?: string
          order_index?: number
          question_text: string
        }
        Update: {
          correct_option?: string
          created_at?: string | null
          exam_id?: string
          id?: string
          marks?: number
          option_a?: string
          option_b?: string
          option_c?: string
          option_d?: string
          order_index?: number
          question_text?: string
        }
        Relationships: [
          {
            foreignKeyName: "cbt_questions_exam_id_fkey"
            columns: ["exam_id"]
            isOneToOne: false
            referencedRelation: "cbt_exams"
            referencedColumns: ["id"]
          },
        ]
      }
      cbt_sessions: {
        Row: {
          created_at: string | null
          exam_id: string
          id: string
          is_submitted: boolean
          started_at: string | null
          student_id: string
          submitted_at: string | null
          total_score: number
        }
        Insert: {
          created_at?: string | null
          exam_id: string
          id?: string
          is_submitted?: boolean
          started_at?: string | null
          student_id: string
          submitted_at?: string | null
          total_score?: number
        }
        Update: {
          created_at?: string | null
          exam_id?: string
          id?: string
          is_submitted?: boolean
          started_at?: string | null
          student_id?: string
          submitted_at?: string | null
          total_score?: number
        }
        Relationships: [
          {
            foreignKeyName: "cbt_sessions_exam_id_fkey"
            columns: ["exam_id"]
            isOneToOne: false
            referencedRelation: "cbt_exams"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cbt_sessions_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      classes: {
        Row: {
          academic_year: string
          capacity: number | null
          created_at: string | null
          id: string
          level: Database["public"]["Enums"]["class_level"]
          name: string
          teacher_id: string | null
        }
        Insert: {
          academic_year?: string
          capacity?: number | null
          created_at?: string | null
          id?: string
          level: Database["public"]["Enums"]["class_level"]
          name: string
          teacher_id?: string | null
        }
        Update: {
          academic_year?: string
          capacity?: number | null
          created_at?: string | null
          id?: string
          level?: Database["public"]["Enums"]["class_level"]
          name?: string
          teacher_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "classes_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      course_materials: {
        Row: {
          course_id: string | null
          created_at: string | null
          description: string | null
          file_storage_path: string | null
          id: string
          title: string
          type: string | null
          uploaded_by: string | null
          url: string | null
        }
        Insert: {
          course_id?: string | null
          created_at?: string | null
          description?: string | null
          file_storage_path?: string | null
          id?: string
          title: string
          type?: string | null
          uploaded_by?: string | null
          url?: string | null
        }
        Update: {
          course_id?: string | null
          created_at?: string | null
          description?: string | null
          file_storage_path?: string | null
          id?: string
          title?: string
          type?: string | null
          uploaded_by?: string | null
          url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "course_materials_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "course_materials_uploaded_by_fkey"
            columns: ["uploaded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      courses: {
        Row: {
          academic_year: string
          class_id: string | null
          created_at: string | null
          description: string | null
          id: string
          is_active: boolean | null
          subject: string
          teacher_id: string | null
          term: string
          title: string
        }
        Insert: {
          academic_year?: string
          class_id?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          subject: string
          teacher_id?: string | null
          term?: string
          title: string
        }
        Update: {
          academic_year?: string
          class_id?: string | null
          created_at?: string | null
          description?: string | null
          id?: string
          is_active?: boolean | null
          subject?: string
          teacher_id?: string | null
          term?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "courses_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "courses_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      events: {
        Row: {
          created_at: string | null
          created_by: string | null
          description: string | null
          end_date: string | null
          event_type: string | null
          id: string
          start_date: string
          target_audience: string[] | null
          title: string
        }
        Insert: {
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          end_date?: string | null
          event_type?: string | null
          id?: string
          start_date: string
          target_audience?: string[] | null
          title: string
        }
        Update: {
          created_at?: string | null
          created_by?: string | null
          description?: string | null
          end_date?: string | null
          event_type?: string | null
          id?: string
          start_date?: string
          target_audience?: string[] | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "events_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      fee_templates: {
        Row: {
          academic_year: string
          amount: number
          applies_to_class: string | null
          created_at: string | null
          fee_type: string
          id: string
          name: string
          term: string
        }
        Insert: {
          academic_year?: string
          amount: number
          applies_to_class?: string | null
          created_at?: string | null
          fee_type: string
          id?: string
          name: string
          term: string
        }
        Update: {
          academic_year?: string
          amount?: number
          applies_to_class?: string | null
          created_at?: string | null
          fee_type?: string
          id?: string
          name?: string
          term?: string
        }
        Relationships: [
          {
            foreignKeyName: "fee_templates_applies_to_class_fkey"
            columns: ["applies_to_class"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
        ]
      }
      fees: {
        Row: {
          academic_year: string
          amount: number
          created_at: string | null
          due_date: string
          fee_type: string
          id: string
          paid_amount: number | null
          status: Database["public"]["Enums"]["fee_status"]
          student_id: string | null
          term: string
        }
        Insert: {
          academic_year?: string
          amount: number
          created_at?: string | null
          due_date: string
          fee_type: string
          id?: string
          paid_amount?: number | null
          status?: Database["public"]["Enums"]["fee_status"]
          student_id?: string | null
          term: string
        }
        Update: {
          academic_year?: string
          amount?: number
          created_at?: string | null
          due_date?: string
          fee_type?: string
          id?: string
          paid_amount?: number | null
          status?: Database["public"]["Enums"]["fee_status"]
          student_id?: string | null
          term?: string
        }
        Relationships: [
          {
            foreignKeyName: "fees_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      grades: {
        Row: {
          academic_year: string
          assessment_type: string
          created_at: string | null
          graded_by: string | null
          id: string
          max_score: number
          score: number
          student_id: string | null
          subject: string
          term: string
        }
        Insert: {
          academic_year?: string
          assessment_type: string
          created_at?: string | null
          graded_by?: string | null
          id?: string
          max_score?: number
          score: number
          student_id?: string | null
          subject: string
          term: string
        }
        Update: {
          academic_year?: string
          assessment_type?: string
          created_at?: string | null
          graded_by?: string | null
          id?: string
          max_score?: number
          score?: number
          student_id?: string | null
          subject?: string
          term?: string
        }
        Relationships: [
          {
            foreignKeyName: "grades_graded_by_fkey"
            columns: ["graded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "grades_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      health_records: {
        Row: {
          created_at: string | null
          date_recorded: string | null
          description: string
          id: string
          record_type: string
          recorded_by: string | null
          student_id: string | null
        }
        Insert: {
          created_at?: string | null
          date_recorded?: string | null
          description: string
          id?: string
          record_type: string
          recorded_by?: string | null
          student_id?: string | null
        }
        Update: {
          created_at?: string | null
          date_recorded?: string | null
          description?: string
          id?: string
          record_type?: string
          recorded_by?: string | null
          student_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "health_records_recorded_by_fkey"
            columns: ["recorded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "health_records_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      in_app_notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          link_id: string | null
          link_kind: string | null
          profile_id: string
          read_at: string | null
          title: string
          type: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          link_id?: string | null
          link_kind?: string | null
          profile_id: string
          read_at?: string | null
          title: string
          type?: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          link_id?: string | null
          link_kind?: string | null
          profile_id?: string
          read_at?: string | null
          title?: string
          type?: string
        }
        Relationships: [
          {
            foreignKeyName: "in_app_notifications_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      lesson_plans: {
        Row: {
          activities: string | null
          assessment: string | null
          course_id: string
          created_at: string
          differentiation: string | null
          id: string
          lesson_date: string | null
          materials_needed: string | null
          objectives: string | null
          reflection_notes: string | null
          review_note: string | null
          reviewed_at: string | null
          reviewed_by: string | null
          status: string
          teacher_profile_id: string
          title: string
          updated_at: string
        }
        Insert: {
          activities?: string | null
          assessment?: string | null
          course_id: string
          created_at?: string
          differentiation?: string | null
          id?: string
          lesson_date?: string | null
          materials_needed?: string | null
          objectives?: string | null
          reflection_notes?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          teacher_profile_id: string
          title: string
          updated_at?: string
        }
        Update: {
          activities?: string | null
          assessment?: string | null
          course_id?: string
          created_at?: string
          differentiation?: string | null
          id?: string
          lesson_date?: string | null
          materials_needed?: string | null
          objectives?: string | null
          reflection_notes?: string | null
          review_note?: string | null
          reviewed_at?: string | null
          reviewed_by?: string | null
          status?: string
          teacher_profile_id?: string
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "lesson_plans_course_id_fkey"
            columns: ["course_id"]
            isOneToOne: false
            referencedRelation: "courses"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_plans_reviewed_by_fkey"
            columns: ["reviewed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "lesson_plans_teacher_profile_id_fkey"
            columns: ["teacher_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          body: string
          created_at: string | null
          id: string
          is_read: boolean
          parent_message_id: string | null
          recipient_id: string | null
          sender_id: string
          subject: string
          target_role: string | null
        }
        Insert: {
          body: string
          created_at?: string | null
          id?: string
          is_read?: boolean
          parent_message_id?: string | null
          recipient_id?: string | null
          sender_id: string
          subject?: string
          target_role?: string | null
        }
        Update: {
          body?: string
          created_at?: string | null
          id?: string
          is_read?: boolean
          parent_message_id?: string | null
          recipient_id?: string | null
          sender_id?: string
          subject?: string
          target_role?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "messages_parent_message_id_fkey"
            columns: ["parent_message_id"]
            isOneToOne: false
            referencedRelation: "messages"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "messages_sender_id_fkey"
            columns: ["sender_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      parents: {
        Row: {
          address: string | null
          created_at: string | null
          id: string
          occupation: string | null
          profile_id: string | null
          relationship_to_student: string | null
          workplace: string | null
        }
        Insert: {
          address?: string | null
          created_at?: string | null
          id?: string
          occupation?: string | null
          profile_id?: string | null
          relationship_to_student?: string | null
          workplace?: string | null
        }
        Update: {
          address?: string | null
          created_at?: string | null
          id?: string
          occupation?: string | null
          profile_id?: string | null
          relationship_to_student?: string | null
          workplace?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "parents_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string | null
          email: string
          first_name: string
          id: string
          last_name: string
          phone: string | null
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string | null
          user_id: string | null
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string | null
          email: string
          first_name?: string
          id?: string
          last_name?: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string | null
          user_id?: string | null
        }
        Update: {
          avatar_url?: string | null
          created_at?: string | null
          email?: string
          first_name?: string
          id?: string
          last_name?: string
          phone?: string | null
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      result_sheets: {
        Row: {
          academic_year: string
          attentiveness: number | null
          cooperation: number | null
          created_at: string | null
          created_by: string | null
          days_absent: number
          days_present: number
          honesty: number | null
          id: string
          is_published: boolean
          neatness: number | null
          next_term_begins: string | null
          next_term_fees: string
          politeness: number | null
          principal_comment: string
          punctuality: number | null
          student_id: string
          teacher_comment: string
          term: string
          total_school_days: number
          updated_at: string | null
        }
        Insert: {
          academic_year: string
          attentiveness?: number | null
          cooperation?: number | null
          created_at?: string | null
          created_by?: string | null
          days_absent?: number
          days_present?: number
          honesty?: number | null
          id?: string
          is_published?: boolean
          neatness?: number | null
          next_term_begins?: string | null
          next_term_fees?: string
          politeness?: number | null
          principal_comment?: string
          punctuality?: number | null
          student_id: string
          teacher_comment?: string
          term: string
          total_school_days?: number
          updated_at?: string | null
        }
        Update: {
          academic_year?: string
          attentiveness?: number | null
          cooperation?: number | null
          created_at?: string | null
          created_by?: string | null
          days_absent?: number
          days_present?: number
          honesty?: number | null
          id?: string
          is_published?: boolean
          neatness?: number | null
          next_term_begins?: string | null
          next_term_fees?: string
          politeness?: number | null
          principal_comment?: string
          punctuality?: number | null
          student_id?: string
          teacher_comment?: string
          term?: string
          total_school_days?: number
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "result_sheets_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "result_sheets_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      school_settings: {
        Row: {
          id: string
          key: string
          updated_at: string | null
          value: Json
        }
        Insert: {
          id?: string
          key: string
          updated_at?: string | null
          value?: Json
        }
        Update: {
          id?: string
          key?: string
          updated_at?: string | null
          value?: Json
        }
        Relationships: []
      }
      subject_settings: {
        Row: {
          id: string
          level_group: string
          subject: string
          is_visible: boolean
          sort_order: number
        }
        Insert: {
          id?: string
          level_group: string
          subject: string
          is_visible?: boolean
          sort_order?: number
        }
        Update: {
          id?: string
          level_group?: string
          subject?: string
          is_visible?: boolean
          sort_order?: number
        }
        Relationships: []
      }
      student_parents: {
        Row: {
          created_at: string | null
          id: string
          is_primary: boolean | null
          parent_id: string | null
          student_id: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_primary?: boolean | null
          parent_id?: string | null
          student_id?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          is_primary?: boolean | null
          parent_id?: string | null
          student_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "student_parents_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "parents"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "student_parents_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      students: {
        Row: {
          address: string | null
          class_id: string | null
          created_at: string | null
          date_of_birth: string | null
          emergency_contact: string | null
          emergency_phone: string | null
          enrollment_date: string | null
          gender: string | null
          id: string
          is_active: boolean | null
          medical_conditions: string | null
          profile_id: string | null
          student_id: string
        }
        Insert: {
          address?: string | null
          class_id?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          emergency_contact?: string | null
          emergency_phone?: string | null
          enrollment_date?: string | null
          gender?: string | null
          id?: string
          is_active?: boolean | null
          medical_conditions?: string | null
          profile_id?: string | null
          student_id: string
        }
        Update: {
          address?: string | null
          class_id?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          emergency_contact?: string | null
          emergency_phone?: string | null
          enrollment_date?: string | null
          gender?: string | null
          id?: string
          is_active?: boolean | null
          medical_conditions?: string | null
          profile_id?: string | null
          student_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "students_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "students_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      subjects: {
        Row: {
          academic_year: string
          class_id: string | null
          code: string | null
          created_at: string | null
          id: string
          is_active: boolean | null
          name: string
          teacher_id: string | null
          term: string
        }
        Insert: {
          academic_year?: string
          class_id?: string | null
          code?: string | null
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          name: string
          teacher_id?: string | null
          term?: string
        }
        Update: {
          academic_year?: string
          class_id?: string | null
          code?: string | null
          created_at?: string | null
          id?: string
          is_active?: boolean | null
          name?: string
          teacher_id?: string | null
          term?: string
        }
        Relationships: [
          {
            foreignKeyName: "subjects_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "subjects_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      submissions: {
        Row: {
          assignment_id: string | null
          content: string | null
          feedback: string | null
          file_url: string | null
          graded_at: string | null
          graded_by: string | null
          id: string
          score: number | null
          status: string | null
          student_id: string | null
          submitted_at: string | null
          work_document_path: string | null
          work_image_path: string | null
        }
        Insert: {
          assignment_id?: string | null
          content?: string | null
          feedback?: string | null
          file_url?: string | null
          graded_at?: string | null
          graded_by?: string | null
          id?: string
          score?: number | null
          status?: string | null
          student_id?: string | null
          submitted_at?: string | null
          work_document_path?: string | null
          work_image_path?: string | null
        }
        Update: {
          assignment_id?: string | null
          content?: string | null
          feedback?: string | null
          file_url?: string | null
          graded_at?: string | null
          graded_by?: string | null
          id?: string
          score?: number | null
          status?: string | null
          student_id?: string | null
          submitted_at?: string | null
          work_document_path?: string | null
          work_image_path?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "submissions_assignment_id_fkey"
            columns: ["assignment_id"]
            isOneToOne: false
            referencedRelation: "assignments"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_graded_by_fkey"
            columns: ["graded_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
      teachers: {
        Row: {
          created_at: string | null
          employee_id: string
          hire_date: string | null
          id: string
          is_active: boolean | null
          profile_id: string | null
          qualification: string | null
          salary: number | null
          specialization: string | null
        }
        Insert: {
          created_at?: string | null
          employee_id: string
          hire_date?: string | null
          id?: string
          is_active?: boolean | null
          profile_id?: string | null
          qualification?: string | null
          salary?: number | null
          specialization?: string | null
        }
        Update: {
          created_at?: string | null
          employee_id?: string
          hire_date?: string | null
          id?: string
          is_active?: boolean | null
          profile_id?: string | null
          qualification?: string | null
          salary?: number | null
          specialization?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "teachers_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      timetable: {
        Row: {
          academic_year: string
          class_id: string
          created_at: string | null
          day_of_week: string
          end_time: string
          id: string
          period: number
          start_time: string
          subject: string
          teacher_id: string | null
          term: string
        }
        Insert: {
          academic_year?: string
          class_id: string
          created_at?: string | null
          day_of_week: string
          end_time: string
          id?: string
          period: number
          start_time: string
          subject: string
          teacher_id?: string | null
          term?: string
        }
        Update: {
          academic_year?: string
          class_id?: string
          created_at?: string | null
          day_of_week?: string
          end_time?: string
          id?: string
          period?: number
          start_time?: string
          subject?: string
          teacher_id?: string | null
          term?: string
        }
        Relationships: [
          {
            foreignKeyName: "timetable_class_id_fkey"
            columns: ["class_id"]
            isOneToOne: false
            referencedRelation: "classes"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "timetable_teacher_id_fkey"
            columns: ["teacher_id"]
            isOneToOne: false
            referencedRelation: "teachers"
            referencedColumns: ["id"]
          },
        ]
      }
      transport: {
        Row: {
          created_at: string | null
          dropoff_location: string
          dropoff_time: string
          id: string
          is_active: boolean | null
          monthly_fee: number | null
          pickup_location: string
          pickup_time: string
          route_name: string
          student_id: string | null
        }
        Insert: {
          created_at?: string | null
          dropoff_location: string
          dropoff_time: string
          id?: string
          is_active?: boolean | null
          monthly_fee?: number | null
          pickup_location: string
          pickup_time: string
          route_name: string
          student_id?: string | null
        }
        Update: {
          created_at?: string | null
          dropoff_location?: string
          dropoff_time?: string
          id?: string
          is_active?: boolean | null
          monthly_fee?: number | null
          pickup_location?: string
          pickup_time?: string
          route_name?: string
          student_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "transport_student_id_fkey"
            columns: ["student_id"]
            isOneToOne: false
            referencedRelation: "students"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      _notify_admins_lesson_plan_submitted: {
        Args: { p_plan: Database["public"]["Tables"]["lesson_plans"]["Row"] }
        Returns: undefined
      }
      _notify_teacher_lesson_plan_decision: {
        Args: { p_plan: Database["public"]["Tables"]["lesson_plans"]["Row"] }
        Returns: undefined
      }
      admin_create_user: {
        Args: {
          user_email: string
          user_first_name: string
          user_last_name: string
          user_password: string
          profile_role?: 'admin' | 'teacher' | 'parent' | 'student'
        }
        Returns: string
      }
      admin_delete_user: {
        Args: { target_user_id: string }
        Returns: undefined
      }
      admin_reset_password: {
        Args: { new_password: string; target_user_id: string }
        Returns: undefined
      }
      is_admin: { Args: never; Returns: boolean }
      is_parent_of: { Args: { target_student_id: string }; Returns: boolean }
      is_teacher_or_admin: { Args: never; Returns: boolean }
      promote_students: {
        Args: {
          p_from_class_id: string
          p_student_ids?: string[]
          p_to_class_id: string
        }
        Returns: number
      }
      submit_admission_application: {
        Args: {
          p_address: string
          p_child_age?: string
          p_child_name: string
          p_date_of_birth?: string
          p_email: string
          p_emergency_contact: string
          p_emergency_phone: string
          p_gender?: string
          p_medical_conditions?: string
          p_message?: string
          p_parent_name: string
          p_phone: string
          p_previous_school?: string
          p_program: string
        }
        Returns: string
      }
      submit_cbt_exam: { Args: { p_session_id: string }; Returns: Json }
      teacher_assign_student: {
        Args: { p_class_id: string; p_student_id: string }
        Returns: undefined
      }
      user_can_access_course_for_materials: {
        Args: { p_course_id: string }
        Returns: boolean
      }
    }
    Enums: {
      attendance_status: "present" | "absent" | "late" | "excused"
      class_level:
        | "creche"
        | "toddler"
        | "basic1"
        | "basic2"
        | "basic3"
        | "basic4"
        | "basic5"
      fee_status: "pending" | "partial" | "paid" | "overdue"
      user_role: "admin" | "teacher" | "parent" | "student"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  graphql_public: {
    Enums: {},
  },
  public: {
    Enums: {
      attendance_status: ["present", "absent", "late", "excused"],
      class_level: [
        "creche",
        "toddler",
        "basic1",
        "basic2",
        "basic3",
        "basic4",
        "basic5",
      ],
      fee_status: ["pending", "partial", "paid", "overdue"],
      user_role: ["admin", "teacher", "parent", "student"],
    },
  },
} as const
